import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);


// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhSlgPEEnDQonK-0-TnfK62ynyL9CIRXU',
    appId: '1:795973906055:web:ffd5f08fd3927f88499222',
    messagingSenderId: '795973906055',
    projectId: 'c-time-2410c',
    authDomain: 'c-time-2410c.firebaseapp.com',
    storageBucket: 'c-time-2410c.firebasestorage.app',
    measurementId: 'G-QWG0KWR6B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ApoA9CyliH_nIfpNe8Q7vVUxT1_gtZY',
    appId: '1:795973906055:android:721c6404e011d0f6499222',
    messagingSenderId: '795973906055',
    projectId: 'c-time-2410c',
    storageBucket: 'c-time-2410c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyaTdc2SZrnGL-_EhLhJMJyGMV61hvdS8',
    appId: '1:795973906055:ios:723c67bb91bc6b79499222',
    messagingSenderId: '795973906055',
    projectId: 'c-time-2410c',
    storageBucket: 'c-time-2410c.firebasestorage.app',
    iosBundleId: 'com.example.proyecto112',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyaTdc2SZrnGL-_EhLhJMJyGMV61hvdS8',
    appId: '1:795973906055:ios:723c67bb91bc6b79499222',
    messagingSenderId: '795973906055',
    projectId: 'c-time-2410c',
    storageBucket: 'c-time-2410c.firebasestorage.app',
    iosBundleId: 'com.example.proyecto112',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhSlgPEEnDQonK-0-TnfK62ynyL9CIRXU',
    appId: '1:795973906055:web:3eea75b01697d01c499222',
    messagingSenderId: '795973906055',
    projectId: 'c-time-2410c',
    authDomain: 'c-time-2410c.firebaseapp.com',
    storageBucket: 'c-time-2410c.firebasestorage.app',
    measurementId: 'G-HDGZQ0R8LB',
  );
}
